#-------------DEV ENVIRONMENT CONFIGURATION-----------------
base.url=https://eventhub.rahulshettyacademy.com/
browser=chromium
default.timeout=10000
navigation.timeout=30000
environment=dev
#-------------API CONFIGURATION-----------------
api.base.url=https://api.eventhub.rahulshettyacademy.com
api.timeout=10
headless=true
